#!/bin/bash

set -e

# binutils
pushd .
cd binutils
INSTALL_DIR="${PWD}/install"
tar xf binutils-2.35.tar.xz
mkdir build
cd build
../binutils-2.35/configure --prefix=/opt/mips64el-toolchain --build=x86_64-unknown-linux-gnu --host=x86_64-unknown-linux-gnu --target=mips64el-unknown-linux-gnu --with-sysroot=/opt/mips64el-toolchain/platforms/current --enable-64-bit-bfd --enable-ld=default --enable-gold --enable-plugins --enable-threads --with-pic --enable-shared --disable-werror --enable-multilib
make configure-host
make -j4
make DESTDIR=${INSTALL_DIR} install-strip
cp -a ${INSTALL_DIR}/opt/mips64el-toolchain /opt/
popd

