#!/bin/bash

set -e

# linux
pushd .
cd linux
INSTALL_DIR="${PWD}/install"
tar xf linux-5.9.tar.gz
cd linux-5.9
make ARCH=mips INSTALL_HDR_PATH=${INSTALL_DIR} headers_install
find ${INSTALL_DIR} -name .install -delete
find ${INSTALL_DIR} -name ..install.cmd -delete
popd

